# Generated by Django 4.2.30 on 2026-05-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(unique=True)),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacher_salary', models.FloatField()),
                ('teacher_email', models.EmailField(max_length=254, unique=True)),
                ('teaching_subject', models.CharField(choices=[('T', 'TELUGU'), ('H', 'HINDI'), ('E', 'ENGLISH'), ('M', 'MATHS'), ('S', 'SCIENCE'), ('SO', 'SOCIAL')], max_length=20)),
            ],
        ),
    ]
